# Generated by Django 6.0.1 on 2026-03-18 18:06

import appa_bot.models
import django.contrib.postgres.fields
import django.db.models.deletion
import mirage.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Interessado', 'Em teste'), ('Cliente', 'Cliente')], max_length=100, verbose_name='Stakeholder')),
                ('nome_razaosocial', models.CharField(max_length=100, verbose_name='Nome / Razão Social')),
                ('CPF_CNPJ', mirage.fields.EncryptedCharField(max_length=100, verbose_name='CPF/CNPJ')),
                ('email', mirage.fields.EncryptedEmailField(max_length=100, verbose_name='E-mail')),
                ('palavras_chave', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(help_text=' digitas as palavra chave ou termos de sua busca separadas por virgula', max_length=5000, verbose_name='Palavras chave'))),
                ('palavras_exclusao', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, help_text=' digitas as palavra chave ou termos de sua busca separadas por virgula', max_length=5000, null=True, verbose_name='Termos para Exclusão da busca'))),
                ('UF', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF'))),
                ('periodo_busca', models.IntegerField(verbose_name='Alcance em dias da busca')),
                ('identificador', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Identificador')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_fim_teste', models.DateTimeField(default=appa_bot.models.fimteste, verbose_name='Fim do Período de Teste')),
            ],
            options={
                'verbose_name': 'Stakeholder',
                'verbose_name_plural': 'Stakeholders',
            },
        ),
        migrations.CreateModel(
            name='logAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(default=None, max_length=255, verbose_name='Acao')),
                ('object_id', models.PositiveIntegerField()),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log Acao',
                'verbose_name_plural': 'Log de Acoes',
                'ordering': ('-data_hora',),
            },
        ),
    ]
