# Generated by Django 6.0.1 on 2026-03-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appa_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='periodo_busca',
        ),
    ]
