# Generated by Django 6.0.1 on 2026-03-18 20:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appa_bot', '0002_remove_stakeholder_periodo_busca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='categoria',
            field=models.CharField(choices=[('Interessado', 'Em teste'), ('Cliente', 'Cliente')], max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='palavras_exclusao',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, help_text=' digitas as palavra chave ou termos de sua busca separadas por virgula', max_length=5000, null=True, verbose_name='Termos para Exclusão da busca'), blank=True, help_text=' digitas as palavra chave ou termos de sua busca separadas por virgula', null=True, verbose_name='Termos para Exclusão da busca'),
        ),
    ]
